name: Flipkart Scheduled Tests

on:
  schedule:
    - cron: "0 1 * * *" # every day at 2AM UTC

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

jobs:
  FlipkartTest:
    uses: ./.github/workflows/basePipeline.yml
    with:
      THREADS: 1
      ALLURE_REPORT_NAME: Flipkart Regression
      ALLURE_REPORT_DEPLOY_FOLDER: Flipkart_Regression_Tests
      TEST_SUITE: testng.xml
      SEND_EMAIL: 'true'
      EMAIL_TITLE: Flipkart Regression Test Report

    secrets: inherit